### PR TITLE
feat: new ai page

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Closes https://github.com/near/near-discovery/issues/1207

### CODE REVIEW

**Comment by shelegdmitriy** [comment]
Leaving it in draft to fix some thing

**Review by calebjacob — APPROVED** [review]
Looks good! Nice work.

**Comment by shelegdmitriy** [comment]
> Looks good! Nice work.

Not sure have you seen the new `/ai` page because I put the wrong url to the main nav menu 🤦‍♂️

**Comment by calebjacob** [comment]
Haha, I noticed I needed to go directly to`/ai` to see your new page 👍

**Pull request merged**
