### PR TITLE
Chain Abstraction

### PR DESCRIPTION
**Pull request by calebjacob**
Closes: https://github.com/near/near-discovery/issues/1261

- Implement new `/chain-abstraction` route based on Figma design and requirements
- https://docs.google.com/document/d/10Ckicshp0_vX_eHxteDR58-k86GVrHBD4KbaCT-wRbo/edit
- https://www.figma.com/design/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-'24-%2F-Website---v3.2024?node-id=1614-9464&m=dev&focus-id=1614-12180

We can safely merge this into our `develop` environment ahead of August 8th for public testing (mostly verifying content and links). Once merged into `develop`, we'll want to hold on merging/deploying `main` until August 8th. I'm currently checking to see if there's a specific time of day we're wanting this to go live.

@vanessadespain feel free to check out the preview build and let me know if you see any changes that need to be made. I created some new thumbnails for some of the media items due to the Figma images being really low quality - feel free to send over different images. Let me know when we have a thumbnail for `Chain Signatures Mainnet Announcement Post`. Thanks!

### CODE REVIEW

**Review by shelegdmitriy — APPROVED** [review]

**Comment by vanessadespain** [comment]
Looks great to me @calebjacob! There's a chance that we may need to update which Luma Calendar we're pulling in but I think this is good for now until we hear otherwise!

**Review by vanessadespain — COMMENTED** [review]
LGTM!

**Comment by vanessadespain** [comment]
@calebjacob I just heard from the Proximity team a request to remove the card "Technical Deep Dive" as the content won't be ready for the Aug 8th launch. The card is located in the Getting Started Section > Learn > Technical Deep Dive.

**Comment by calebjacob** [comment]
@vanessadespain Sounds good - I'll get that taken care of in a new branch.

**Pull request merged**
