### PR TITLE
chore: add new logos to ai page

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Closes https://github.com/near/near-discovery/issues/1225

### CODE REVIEW

**Comment by charleslavon** [comment]
@shelegdmitriy  Exhabits looks strange
Screen Shot 2024-06-27 at 12 02 43 PM

**Comment by shelegdmitriy** [comment]
> Visit Preview

Thanks for catch! Let let re-download and put it once again

**Comment by shelegdmitriy** [comment]
@charleslavon would you mind to check it on your end that the issue is resolved? Seems the image was broken, I re-added and now everything is fine

**Comment by charleslavon** [comment]
@shelegdmitriy   LGTM

**Pull request merged**
